require(ROOT)
LoadModule('RIO')
LoadModule('Hist')
LoadModule('Gpad')

rfilein <- new(TFile,'gamma.root','read')
obj <- rfilein$Get('gamma')
print(obj)
f1 <- new(TF1,obj)
c1<-new(TCanvas,'c1','gamma')
f1$Draw()
c1$Update()
rfilein$Close('')
